### ISSUE TITLE
Remove aware/capable interfaces?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-eventmanager#11]
Hey!

We have removed in Service Manager the various Aware/Capable interfaces to encourage injection. Should we do the same here?

**Comment by weierophinney** [comment]
The "Capable" interfaces indicate something is composed. In the case of
SharedEventsCapable, we need this to allow collaborators ready access to
the shared manager in order to attach shared listeners.

I already removed the Aware interfaces. :wink:
