### ISSUE TITLE
[ZF2] \Zend\EventManager\SharedEventManager performance issue

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-eventmanager#29]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7663
User: @peterr
Created On: 2016-01-23T23:16:29Z
Updated At: 2016-02-13T15:30:49Z
Body
Hi,
Can anybody tell me why `array_key_exists` function is used over and over in the code of `SharedEventManager` class instead of `isset`, simply? Naturally I talk about version 2 (I see that this class is implemented otherwise in version 3). Wouldn't it be better to use `isset` function for better performance and for better logic in the code?

---
### Comment

User: @Ocramius
Created On: 2016-01-24T00:58:23Z
Updated At: 2016-01-24T00:58:23Z
Body
@peterr send a patch: tests are in place to see if it will work anyway :-)

---
### Comment

User: @peterr
Created On: 2016-01-24T03:12:00Z
Updated At: 2016-01-24T03:41:34Z
Body
What branch from https://github.com/zendframework/zend-eventmanager is right to do that?

---
### Comment

User: @Ocramius
Created On: 2016-01-24T14:24:42Z
Updated At: 2016-01-24T14:24:42Z
Body
@peterr yep

---
### Comment

User: @peterr
Created On: 2016-01-24T14:45:38Z
Updated At: 2016-01-28T13:55:50Z
Body
But I see that the master branch includes yet version 3. Is there a special branch for version 2 in the repository? I talk about version 2 of the EventManager component. Version 3, as I see, is implemented otherwise and doesn't have this problem any more.

---
### Comment

User: @Ocramius
Created On: 2016-01-24T14:50:54Z
Updated At: 2016-01-24T14:50:54Z
Body
@peterr 
- `master` = current version (stable, in this case 3.0.x)
- `develop` = next version (new features/unstable, in this case 3.1.x or 4.x, depending on what will happen)
- `legacy` = previous version (2.x, in this case)

---

**Comment by Xerkus** [comment]
as stated by the author version 3 does not have this issue
