### ISSUE TITLE
Migration Guide: ListenerAggregateInterface is not compatible

### ISSUE THREAD

**Issue by thomasvargiu** [zendframework/zend-eventmanager#30]
Running my tests, I find out that `ListenerAggregateInterface` is not compatibile migrating from v2 to v3 due to a Fatal Error for Incompatible Interface.
Seems that every listener implementing that interface should add the second parameter `$priority` before to migrate.

Is it right?

**Comment by weierophinney** [comment]
@thomasvargiu Correct; that is exactly the path we took when migrating the various ZF components to be forwards-compatible with v3.

**Comment by weierophinney** [comment]
@thomasvargiu Do you feel we need to add some verbiage to this effect in the manual? If so, can you indicate the document? Thanks!

**Comment by thomasvargiu** [comment]
@weierophinney I'm sorry, I didn't read [this part](https://zendframework.github.io/zend-eventmanager/migration/changed/#listeneraggregateinterfaceattach).
I think it's enough.

**Comment by karborator** [comment]
So how we should describe our listener at the module config ?

**Comment by froschdesign** [comment]
@karborator 
Please add your comment here: "[#9 - Add a factory for EVM](https://github.com/zendframework/zend-eventmanager/issues/9)"!
