### ISSUE TITLE
Syntax error in EventManager docs

### ISSUE THREAD

**Issue by divix1988** [zendframework/zend-eventmanager#31]
On page: https://docs.zendframework.com/zend-eventmanager/tutorial/ , there is a syntax error:
`$params = )'foo' => 'bar', 'baz' => 'bat'];`
which should be:
`$params = ['foo' => 'bar', 'baz' => 'bat'];`

**Comment by michalbundyra** [comment]
@divix1988 would you like prepare PR with this fix?

**Comment by divix1988** [comment]
@webimpress  just created: https://github.com/zendframework/zend-eventmanager/pull/32

**Comment by michalbundyra** [comment]
@divix1988 Thanks!

**Comment by froschdesign** [comment]
Fixed with #32
