### ISSUE TITLE
Trigger doesn't reset stop propagation

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/zend-eventmanager#34]
I have found issue in apigility https://github.com/zfcampus/zf-apigility/commit/076a21d3b81ea0ee744f73d2d40a383305a6dbb0#diff-c9248b3167fc44af085b81db2e292837R121.

My MvcEvent has stop propagation property set to `true` during dispatch. After this name is changed to event finish. `triggerEvent` method trigger my event, but after first listener stop propagation stops dispatching my event, because it's already affected by event dispatch. My proposition it's to reset always stop propagation property before trigger like here https://github.com/zendframework/zend-eventmanager/blob/release-2.6.3/src/EventManager.php#L211 .
Now `trigger()` and `triggerEvent()` (or `triggerEventUntil`) trigger events with stop propagation = true in different way

**Comment by snapshotpl** [comment]
@weierophinney can you take a look?

**Comment by snapshotpl** [comment]
@weierophinney ?

**Comment by snapshotpl** [comment]
This issue is only v2 related. Here is simple fix https://github.com/zolek86/zend-eventmanager/commit/bacc3c0748f40ccc9c3e718ee9056dbe39e14f92

**Comment by weierophinney** [comment]
I need code I can use to reproduce the issue before I can create a fix.

**Comment by weierophinney** [comment]
Fixed with #68, which released with 2.6.4.
