### ISSUE TITLE
 Parse error: syntax error, unexpected '.' in /var/www/html/ZendSkeletonApplication/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php on line 209

### ISSUE THREAD

**Issue by princeuk** [zendframework/zend-eventmanager#57]
Hi,
I am getting below issue.

" Parse error: syntax error, unexpected '.' in /var/www/html/ZendSkeletonApplication/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php on line 209"

When I have opened the code then found below line 
"  $returnListeners[$priority] = array_merge(...$listOfListeners);"

Please suggest why you are using three times dots "...". is this issue from zend?

Regards,
Urdesh

**Comment by weierophinney** [comment]
That notation is a [splat](http://php.net/splat#functions.variable-arg-list), which is available since PHP 5.6, which is a _requirement of this component_. The error you're receiving is one you'll get in prior PHP versions, which do not support the operator.
